version: 2

builds:
  - id: blue-guy
    main: ./cmd/blue-guy
    binary: blue-guy
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: default
    builds:
      - blue-guy
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"

brews:
  - name: blue-guy
    repository:
      owner: victorarias
      name: homebrew-blue-guy
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/victorarias/blue-guy
    description: Peer-to-peer mob programming tool with FUSE virtual filesystem
    license: MIT
    dependencies:
      - name: fuse-t
    install: |
      bin.install "blue-guy"
    test: |
      assert_match version.to_s, shell_output("#{bin}/blue-guy -version").strip
